# Survey Form 을 생성
POST localhost:8080/api/v1/surveys HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "title": "음식 선호도 조사 1",
  "description": "음식 선호도 조사를 하기 위한 설문 조사 입니다.",
  "surveyItems": [
    {
      "name": "아이템 1",
      "type": "SHORT_ANSWER",
      "description": "디스크립션 1",
      "isRequired": false,
      "options": [
        {
          "name": "떡볶이"
        },
        {
          "name": "피자"
        },
        {
          "name": "치킨"
        }
      ]
    }
  ]
}

###
POST localhost:8080/api/v1/surveys HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "title": "음식 선호도 조사 2",
  "description": "음식 선호도 조사를 하기 위한 설문 조사 입니다.",
  "surveyItems": [
    {
      "name": "음식 1",
      "type": "SHORT_ANSWER",
      "description": "디스크립션 1",
      "isRequired": true,
      "options": []
    }
  ]
}


###
POST localhost:8080/api/v1/surveys HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "title": "음식 선호도 조사 3",
  "description": "음식 선호도 조사를 하기 위한 설문 조사 입니다.",
  "surveyItems": [
    {
      "name": "아이템 1",
      "type": "SINGLE_SELECT",
      "description": "아이템 1 입니다.",
      "isRequired": true,
      "options": [
        {
          "name": "고기"
        },
        {
          "name": "파스타"
        },
        {
          "name": "국밥"
        }
      ]
    },
    {
      "name": "아이템 2",
      "type": "MULTIPLE_SELECT",
      "description": "아이템 2 입니다.",
      "isRequired": true,
      "options": [
        {
          "name": "국수"
        },
        {
          "name": "스테이크"
        },
        {
          "name": "감자튀김"
        }
      ]
    }
  ]
}