spring:
  application:
    name: survey-maker
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/survey
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9232