spring:
  application:
    name: survey-reply
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/survey-reply
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: 127.0.0.1
      port: 6379
server:
  port: 9233

service:
  survey-maker:
    url: http://localhost:9232